version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: abn

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./app:/app
    depends_on:
      - db
    tty: true
    # command: sh -c "pip install -r /app/requirements.txt && python /app/your_script.py"
    # No Command during development